version: '3'
services:
  db_critick:
    image: postgres:latest
    environment:
      POSTGRES_USER: user_critick
      POSTGRES_PASSWORD: critick_db_test
      POSTGRES_DB: db_critick
    ports:
      - "5433:5432"
    networks:
      - critik_network

  backend_critick:
    build:
      context: ./server
    ports:
      - "8000:5000"
    depends_on:
      - db_critick
    networks:
      - critik_network

networks:
  critik_network:
    driver: bridge
